### ISSUE TITLE
Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist

### ISSUE THREAD

**Issue by Joakk1** [lorisleiva/solana-twitter#9]
Hi all,

I'm currently starting to work in the SOLana environment. I found this tutorial extremely well done but I can't get it to work on my macbook M1 (nor on my old intel Macbook).

Every tool is up to date, the HelloWorld tutorial is working as expected.

Neither the anchor test & web app are working, i'm unable to send any Tweet for example. My phantom Wallet is OK, my current account owns 1000SOL and is connected to the web app. 

But I'm systematically facing the same issue with the following stack traces:

In my chrome console, each time i'm trying to send a tweet: 
```
Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist
    at Connection.sendEncodedTransaction (webpack-internal:///./node_modules/@solana/web3.js/lib/index.browser.esm.js:7836:13)
    at async Connection.sendRawTransaction (webpack-internal:///./node_modules/@solana/web3.js/lib/index.browser.esm.js:7797:20)
    at async at (webpack-internal:///./node_modules/@project-serum/anchor/dist/browser/index.js:646:13)
    at async ot.sendAndConfirm (webpack-internal:///./node_modules/@project-serum/anchor/dist/browser/index.js:584:14)
    at async Object.eval [as sendTweet] (webpack-internal:///./node_modules/@project-serum/anchor/dist/browser/index.js:2768:16)
    at async sendTweet (webpack-internal:///./src/api/send-tweet.js:17:3)
    at async send (webpack-internal:///./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/TweetForm.vue?vue&type=script&setup=true&lang=js:49:21)
```

At the anchor test side:
```
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1770 
    Program CDqV8J2Hv4UKZXinj9vhxU9VRZfwvJ7NvBZfBuSgTcJs invoke [1]
    Program log: Instruction: SendTweet
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x1770
    Program CDqV8J2Hv4UKZXinj9vhxU9VRZfwvJ7NvBZfBuSgTcJs consumed 8687 of 200000 compute units
    Program CDqV8J2Hv4UKZXinj9vhxU9VRZfwvJ7NvBZfBuSgTcJs failed: custom program error: 0x1770
    1) cannot provide a topic with more than 50 characters
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1771 
    Program CDqV8J2Hv4UKZXinj9vhxU9VRZfwvJ7NvBZfBuSgTcJs invoke [1]
    Program log: Instruction: SendTweet
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x1771
    Program CDqV8J2Hv4UKZXinj9vhxU9VRZfwvJ7NvBZfBuSgTcJs consumed 10763 of 200000 compute units
    Program CDqV8J2Hv4UKZXinj9vhxU9VRZfwvJ7NvBZfBuSgTcJs failed: custom program error: 0x1771
    2) cannot provide a content with more than 280 characters
```

Any help is welcome to try to understand the error and how I can debug and fix it.

Thanks in advance

**Comment by ThannDev** [comment]
Talk to Solana Support on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

**Comment by Joakk1** [comment]
It was my mistake!!!

Forgot to update the app JSON IDL with the new anchor generated one after deploy. Once done, everything is working as expected!

**Comment by Sky1706** [comment]
Hello @Joakk1 right now i am getting same error while sending transactions using jito bundle.

**Comment by raghav-rama** [comment]
Can you tell your error more specifically? @Joakk1

**Comment by rohit-sekhri51** [comment]
@Joakk1 I am getting the same error, can you please tell how you solved it. I am using idlgeb!() macro
